name: helloworld
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '^3.5.3'

dependencies:
  flutter:
    sdk: flutter
  http: any
  collection: ^1.18.0
  http_parser: ^4.0.2  # تعديل الإصدار ليتوافق مع collection 1.18.0
  leak_tracker: ^10.0.5
  leak_tracker_flutter_testing: ^3.0.5
  lints: ^5.0.0
  material_color_utilities: ^0.11.1
  meta: ^1.15.0
  stack_trace: ^1.11.1
  string_scanner: ^1.2.0
  test_api: ^0.7.2
  vm_service: ^14.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any

flutter:
  uses-material-design: true